### ISSUE TITLE
UITextView seems to have an undocumented maximum text length it can display

### ISSUE THREAD

**Issue by neonichu** [contentful/blog-app-ios#1]
Consider the "Markdown Syntax" example entry, it will not be rendered by default. The scroll view `contentSize` seems to be correct, but no text is visible.

Cutting down the string length like this:

```
let rangedBody = NSString(string: post.body!).substringWithRange(NSRange(location: 0, length: 13282))
```

works, but increasing it to 13283 and beyond exhibits the broken behaviour. At the moment, it is undetermined if this is a hard character limit or related to the number of attributes used for the string as well.

**Comment by neonichu** [comment]
This actually seems to be a problem in the simulator only.

**Comment by seanoshea** [comment]
Thanks for leaving an explanation about this only being a simulator issue. I just ran into this with https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_services.html#a6660d896856f41d19f6409354fd68fc0 and putting attributed text in a `UITextView`
